
# If this is enabled the tool will run in display mode and use the file specified underneath as the displayed file.

display:
  mode: false
  file: 'RDPMSpecIdentifier.json'

# This specifies the maximum selectable kernel range. adjust this if you have a high number of fractions accordingly.
kernel:
  max: !!int 7

