on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-20.04', 'macos-latest']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies and build
      run: |
        pip install -r requirements.txt pyinstaller
        pyinstaller RAPDORexe.spec

    - name: Chmod +x (Linux only)
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest'
      run: chmod +x dist/RAPDOR/RAPDOR

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: RAPDOR_${{ matrix.os }}
        path: dist/*


