on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-20.04', 'macos-latest']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies and build
      run: |
        pip install -r requirements.txt pyinstaller
        pyinstaller RAPDORexe.spec

    - name: Extract version from versioneer
      id: version
      shell: bash
      run: echo "version=$(python -c "import versioneer; print(versioneer.get_version())")" >> $GITHUB_OUTPUT

    - name: rename dist
      shell: bash
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest'
      run: |
        mv dist/RAPDOR dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}
        zip -r dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}.zip dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}

    - name: rename dist and zip on Windows
      if: matrix.os == 'windows-latest'
      run: |
        Move-Item -Path dist/RAPDOR -Destination dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}
        Compress-Archive -Path dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }} -DestinationPath dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}
        path: dist/*

    - name: Release nightly
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: nightly
        tag_name: nightly
        files: dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}.zip
        fail_on_unmatched_files: true


