on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-20.04', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller RAPDORexe.spec
    - uses: actions/upload-artifact@v2
      with:
        name:  RAPDOR_${{ matrix.os }}
        path: dist/*