name: nightly-release
on:
  push:
    branches: [ dev ]




env:
  GITHUB_REPOSITORY: domonik/RAPDOR
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  delete-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: del-tag
        run: |
          RELEASE_ID=$(curl -L -H "Accept: application/vnd.github+json"  -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/domonik/RAPDOR/releases/tags/nightly | jq -r '.id')
          if [ "${RELEASE_ID}" != "null" ]; then
            curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: ${GITHUB_ACTOR} ${GITHUB_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/domonik/RAPDOR/releases/${RELEASE_ID}
          fi
          git push --delete origin nightly || true
          git tag --delete nightly || true

    

  build:
    needs: delete-tag
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-20.04', 'macos-latest', "ubuntu-22.04"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies and build
      run: |
        pip install -r requirements.txt pyinstaller
        pyinstaller RAPDORexe.spec

    - name: Extract version from versioneer
      id: version
      shell: bash
      run: echo "version=$(python -c "import versioneer; print(versioneer.get_version())")" >> $GITHUB_OUTPUT

    - name: rename dist
      shell: bash
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest' || matrix.os == 'ubuntu-22.04'
      run: |
        mv dist/RAPDOR dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}
        cd dist
        zip -r RAPDOR_nightly_${{ matrix.os }}.zip RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}
        cd ..

    - name: rename dist and zip on Windows
      if: matrix.os == 'windows-latest'
      run: |
        Move-Item -Path dist/RAPDOR -Destination dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }}
        Compress-Archive -Path dist/RAPDOR_v${{ steps.version.outputs.version }}_${{ matrix.os }} -DestinationPath dist/RAPDOR_nightly_${{ matrix.os }}.zip

    - name: Release nightly
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        name: nightly
        tag_name: nightly
        target_commitish: dev
        files: dist/RAPDOR_nightly_${{ matrix.os }}.zip
        fail_on_unmatched_files: true


